/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BranchRouteImport } from './routes/branch'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutShipmentsRouteImport } from './routes/dashboard/_layout/shipments'
import { Route as DashboardLayoutSettingsRouteImport } from './routes/dashboard/_layout/settings'
import { Route as DashboardLayoutProfilesRouteImport } from './routes/dashboard/_layout/profiles'
import { Route as DashboardLayoutProfileRouteImport } from './routes/dashboard/_layout/profile'
import { Route as DashboardLayoutProductsRouteImport } from './routes/dashboard/_layout/products'
import { Route as DashboardLayoutPickupsRouteImport } from './routes/dashboard/_layout/pickups'
import { Route as DashboardLayoutInventoryRouteImport } from './routes/dashboard/_layout/inventory'
import { Route as DashboardLayoutBranchesRouteImport } from './routes/dashboard/_layout/branches'
import { Route as DashboardLayoutAccountsRouteImport } from './routes/dashboard/_layout/accounts'
import { Route as DashboardLayoutTestTestIdRouteImport } from './routes/dashboard/_layout/test/$testId'
import { Route as DashboardLayoutProfileProfileIdRouteImport } from './routes/dashboard/_layout/profile/$profileId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchRoute = BranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutShipmentsRoute =
  DashboardLayoutShipmentsRouteImport.update({
    id: '/shipments',
    path: '/shipments',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsRoute = DashboardLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutProfilesRoute = DashboardLayoutProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutProfileRoute = DashboardLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutProductsRoute = DashboardLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutPickupsRoute = DashboardLayoutPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutInventoryRoute =
  DashboardLayoutInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBranchesRoute = DashboardLayoutBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutAccountsRoute = DashboardLayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutTestTestIdRoute =
  DashboardLayoutTestTestIdRouteImport.update({
    id: '/test/$testId',
    path: '/test/$testId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutProfileProfileIdRoute =
  DashboardLayoutProfileProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => DashboardLayoutProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/branch': typeof BranchRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/accounts': typeof DashboardLayoutAccountsRoute
  '/dashboard/branches': typeof DashboardLayoutBranchesRoute
  '/dashboard/inventory': typeof DashboardLayoutInventoryRoute
  '/dashboard/pickups': typeof DashboardLayoutPickupsRoute
  '/dashboard/products': typeof DashboardLayoutProductsRoute
  '/dashboard/profile': typeof DashboardLayoutProfileRouteWithChildren
  '/dashboard/profiles': typeof DashboardLayoutProfilesRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/shipments': typeof DashboardLayoutShipmentsRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/profile/$profileId': typeof DashboardLayoutProfileProfileIdRoute
  '/dashboard/test/$testId': typeof DashboardLayoutTestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/branch': typeof BranchRoute
  '/login': typeof LoginRoute
  '/dashboard/accounts': typeof DashboardLayoutAccountsRoute
  '/dashboard/branches': typeof DashboardLayoutBranchesRoute
  '/dashboard/inventory': typeof DashboardLayoutInventoryRoute
  '/dashboard/pickups': typeof DashboardLayoutPickupsRoute
  '/dashboard/products': typeof DashboardLayoutProductsRoute
  '/dashboard/profile': typeof DashboardLayoutProfileRouteWithChildren
  '/dashboard/profiles': typeof DashboardLayoutProfilesRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/shipments': typeof DashboardLayoutShipmentsRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/profile/$profileId': typeof DashboardLayoutProfileProfileIdRoute
  '/dashboard/test/$testId': typeof DashboardLayoutTestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/branch': typeof BranchRoute
  '/login': typeof LoginRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/_layout/accounts': typeof DashboardLayoutAccountsRoute
  '/dashboard/_layout/branches': typeof DashboardLayoutBranchesRoute
  '/dashboard/_layout/inventory': typeof DashboardLayoutInventoryRoute
  '/dashboard/_layout/pickups': typeof DashboardLayoutPickupsRoute
  '/dashboard/_layout/products': typeof DashboardLayoutProductsRoute
  '/dashboard/_layout/profile': typeof DashboardLayoutProfileRouteWithChildren
  '/dashboard/_layout/profiles': typeof DashboardLayoutProfilesRoute
  '/dashboard/_layout/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/_layout/shipments': typeof DashboardLayoutShipmentsRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/profile/$profileId': typeof DashboardLayoutProfileProfileIdRoute
  '/dashboard/_layout/test/$testId': typeof DashboardLayoutTestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/branch'
    | '/login'
    | '/dashboard'
    | '/dashboard/accounts'
    | '/dashboard/branches'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/'
    | '/dashboard/profile/$profileId'
    | '/dashboard/test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/branch'
    | '/login'
    | '/dashboard/accounts'
    | '/dashboard/branches'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard'
    | '/dashboard/profile/$profileId'
    | '/dashboard/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/branch'
    | '/login'
    | '/dashboard/_layout'
    | '/dashboard/_layout/accounts'
    | '/dashboard/_layout/branches'
    | '/dashboard/_layout/inventory'
    | '/dashboard/_layout/pickups'
    | '/dashboard/_layout/products'
    | '/dashboard/_layout/profile'
    | '/dashboard/_layout/profiles'
    | '/dashboard/_layout/settings'
    | '/dashboard/_layout/shipments'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/profile/$profileId'
    | '/dashboard/_layout/test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  BranchRoute: typeof BranchRoute
  LoginRoute: typeof LoginRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch': {
      id: '/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof BranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/shipments': {
      id: '/dashboard/_layout/shipments'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof DashboardLayoutShipmentsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings': {
      id: '/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/profiles': {
      id: '/dashboard/_layout/profiles'
      path: '/profiles'
      fullPath: '/dashboard/profiles'
      preLoaderRoute: typeof DashboardLayoutProfilesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/profile': {
      id: '/dashboard/_layout/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardLayoutProfileRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/products': {
      id: '/dashboard/_layout/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardLayoutProductsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/pickups': {
      id: '/dashboard/_layout/pickups'
      path: '/pickups'
      fullPath: '/dashboard/pickups'
      preLoaderRoute: typeof DashboardLayoutPickupsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/inventory': {
      id: '/dashboard/_layout/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardLayoutInventoryRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/branches': {
      id: '/dashboard/_layout/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof DashboardLayoutBranchesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/accounts': {
      id: '/dashboard/_layout/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardLayoutAccountsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/test/$testId': {
      id: '/dashboard/_layout/test/$testId'
      path: '/test/$testId'
      fullPath: '/dashboard/test/$testId'
      preLoaderRoute: typeof DashboardLayoutTestTestIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/profile/$profileId': {
      id: '/dashboard/_layout/profile/$profileId'
      path: '/$profileId'
      fullPath: '/dashboard/profile/$profileId'
      preLoaderRoute: typeof DashboardLayoutProfileProfileIdRouteImport
      parentRoute: typeof DashboardLayoutProfileRoute
    }
  }
}

interface DashboardLayoutProfileRouteChildren {
  DashboardLayoutProfileProfileIdRoute: typeof DashboardLayoutProfileProfileIdRoute
}

const DashboardLayoutProfileRouteChildren: DashboardLayoutProfileRouteChildren =
  {
    DashboardLayoutProfileProfileIdRoute: DashboardLayoutProfileProfileIdRoute,
  }

const DashboardLayoutProfileRouteWithChildren =
  DashboardLayoutProfileRoute._addFileChildren(
    DashboardLayoutProfileRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutAccountsRoute: typeof DashboardLayoutAccountsRoute
  DashboardLayoutBranchesRoute: typeof DashboardLayoutBranchesRoute
  DashboardLayoutInventoryRoute: typeof DashboardLayoutInventoryRoute
  DashboardLayoutPickupsRoute: typeof DashboardLayoutPickupsRoute
  DashboardLayoutProductsRoute: typeof DashboardLayoutProductsRoute
  DashboardLayoutProfileRoute: typeof DashboardLayoutProfileRouteWithChildren
  DashboardLayoutProfilesRoute: typeof DashboardLayoutProfilesRoute
  DashboardLayoutSettingsRoute: typeof DashboardLayoutSettingsRoute
  DashboardLayoutShipmentsRoute: typeof DashboardLayoutShipmentsRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutTestTestIdRoute: typeof DashboardLayoutTestTestIdRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutAccountsRoute: DashboardLayoutAccountsRoute,
  DashboardLayoutBranchesRoute: DashboardLayoutBranchesRoute,
  DashboardLayoutInventoryRoute: DashboardLayoutInventoryRoute,
  DashboardLayoutPickupsRoute: DashboardLayoutPickupsRoute,
  DashboardLayoutProductsRoute: DashboardLayoutProductsRoute,
  DashboardLayoutProfileRoute: DashboardLayoutProfileRouteWithChildren,
  DashboardLayoutProfilesRoute: DashboardLayoutProfilesRoute,
  DashboardLayoutSettingsRoute: DashboardLayoutSettingsRoute,
  DashboardLayoutShipmentsRoute: DashboardLayoutShipmentsRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutTestTestIdRoute: DashboardLayoutTestTestIdRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  BranchRoute: BranchRoute,
  LoginRoute: LoginRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
